version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=dball
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - 3306:3306

    webserver:
        image: nginx:alpine
        container_name: webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 81:80

    php-fpm:
        build: docker/php-fpm
        container_name: php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/90-overrides.ini

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - mysql
        ports:
            - 8080:80
        environment:
            MYSQL_USERNAME: user
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: mysql