#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_registre:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

